name: Bat-Man Pixel Art
dims: [24, 25, 1]
tags: ['movie character', 'cartoon character', 'batman', 'comic book character', 'pixel art', 'movie character', 'cartoon character', 'comic book character', 'pixel art']
