name: Small Medieval Rustic Starter Home 
dims: [12, 8, 15]
tags: ['medieval', ' building', 'small medieval house', ' house', ' medieval house', 'rustic starter home', ' building', 'small medieval house', ' house', ' medieval house', 'rustic starter home']
