name: Deadpool Statue
dims: [16, 32, 8]
tags: ['statue', 'fictional', 'character', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'antihero', 'deadpool', 'movie character', 'cartoon character', 'comic book character', 'supervillain']
