name: Shady Medieval House 5
dims: [18, 22, 14]
tags: ['medieval', ' medieval house', 'shady', 'shady house', ' house', 'unfurnished', 'unfurnished house', 'unfurnished medieval house', 'exterior only']
