name: Medieval Middle Class House 21
dims: [19, 11, 13]
tags: ['medieval', ' building', ' house', 'middle class house', ' medieval house', ' building', ' house', 'middle class house', ' medieval house']
