name: Mabel Pines (Gravity Falls)
dims: [71, 76, 1]
tags: ['cartoon character', 'cartoon', 'pixel art', 'mabel pines', 'gravity falls', 'cartoon character', 'pixel art', 'mabel pines', 'gravity falls']
