name: Minion Statue
dims: [16, 33, 10]
tags: [' statue', 'fictional', 'character', 'minion', 'cartoon character', 'universal studios', 'despicable me', ' statue', 'cartoon character', 'universal studios', 'despicable me']
