name: Brian (Family Guy)
dims: [50, 81, 1]
tags: ['statue', 'fictional', 'cartoon character', 'tv series character', 'the family guy', 'brian', 'cartoon character', 'tv series character', 'the family guy']
