name: Enchanting Table Statue
dims: [16, 18, 16]
tags: [' statue', 'minecraft item', 'item', 'technical block', 'enchanting table', ' statue', 'minecraft item', 'technical block', 'enchanting table']
