name: Green Arrow Statue
dims: [16, 33, 8]
tags: ['statue', 'fictional', 'character', 'movie character', 'comic book character', 'dc comics', 'tv series character', 'green arrow', 'movie character', 'comic book character', 'dc comics', 'tv series character', 'green arrow']
