name: Modern Mountain House
dims: [31, 11, 27]
tags: ['house', 'modern house', 'modern', ' building', 'modern mountain house', 'mountain house', 'modern house', ' building', 'modern mountain house', 'mountain house']
