name: Simple Survival House
dims: [32, 16, 29]
tags: ['survival house', ' building', 'simple house', ' house', 'simple survival house', 'survival house', ' building', 'simple house', ' house', 'simple survival house']
