name: Link
dims: [15, 15, 1]
tags: ['cartoon character', 'comic book character', 'nintendo', 'link', 'the legend of zelda', 'cartoon character', 'comic book character', 'the legend of zelda', 'pixel art']
