name: Shady Medieval House 3
dims: [27, 25, 20]
tags: ['shady', 'shady house', 'medieval', ' medieval house', ' house', 'unfurnished', 'unfurnished house', 'unfurnished medieval house', 'exterior only']
