name: Medieval Fishing Sailboat
dims: [13, 10, 5]
tags: ['fishing', 'medieval', 'sailboat', 'fishing boat', 'sail boat', 'medieval sailboat', 'small fishing boat', 'fishing boat', 'sail boat', 'medieval sailboat', 'small fishing boat']
