name: Homer Simpson Statue
dims: [16, 36, 10]
tags: ['statue', 'fictional', 'character', 'cartoon character', 'tv series character', 'the simpsons', 'homer simpson', 'cartoon character', 'tv series character', 'the simpsons', 'homer simpson']
