name: Item Transportation System
dims: [5, 7, 15]
tags: ['redstone', 'working mechanism', 'machine', ' mechanisms', 'item transportation system', 'working mechanism', ' mechanisms', 'item transportation system']
