name: Waterfall Survival House
dims: [28, 13, 19]
tags: ['survival', 'survival house', ' building', 'waterfall survival house', 'waterfall', 'survival house', ' building', 'waterfall survival house']
