name: Black Widow Statue (The Avengers)
dims: [18, 32, 8]
tags: [' statue', 'movie character', 'the avengers', 'black widow statue', ' statue', 'movie character', 'the avengers', 'black widow statue']
