name: Patrick Star
dims: [31, 47, 1]
tags: ['fictional', 'cartoon character', 'tv series character', 'spongebob', 'patrick star', 'cartoon character', 'tv series character', 'patrick star', 'pixel art']
