name: Fully Extended Carrier Platform
dims: [7, 12, 9]
tags: ['transportation', 'vehicle', 'working vehicle', 'support vehicle', 'carrier platform', 'working vehicle', 'support vehicle', 'carrier platform']
