name: Zombie
dims: [28, 42, 1]
tags: ['zombie', 'movie character', 'cartoon character', 'comic book character', 'video game character', 'pixel art', 'movie character', 'cartoon character', 'comic book character', 'video game character', 'pixel art']
