name: Small Medieval Victorian House
dims: [19, 17, 21]
tags: ['medieval', 'small house', ' building', ' house', 'medieval victorian house', 'small house', ' building', ' house', 'medieval victorian house']
