name: Low Class Medieval House 14
dims: [15, 10, 12]
tags: ['medieval', ' building', ' house', ' medieval house', 'class medieval house', ' building', ' house', ' medieval house', 'class medieval house']
