name: Underwater Survival House
dims: [35, 16, 21]
tags: ['survival house', ' building', 'underwater survival house', 'underwater house', 'survival house', ' building', 'underwater survival house', 'underwater house']
