name: Small Rustic Starter Home
dims: [11, 15, 11]
tags: [' building', ' house', 'rustic', 'rustic starter home', 'small rustic house', ' building', ' house', 'rustic starter home', 'small rustic house']
