name: Runiya Medieval Stables
dims: [29, 17, 25]
tags: ['runiya', 'medieval', ' medieval house', 'medieval stable', 'stables', 'medieval barn/stables', 'unfurnished', 'unfurnished house', 'unfurnished medieval house']
