name: Modern Desert House
dims: [27, 7, 27]
tags: ['modern house', 'desert house', ' building', ' house', 'modern desert house', 'modern house', 'desert house', ' building', ' house', 'modern desert house']
