name: Kirby
dims: [15, 15, 1]
tags: ['fictional', 'cartoon character', 'comic book character', 'video game character', 'nintendo', 'kirby', 'cartoon character', 'comic book character', 'video game character', 'pixel art']
