name: Fantasy Island House
dims: [26, 33, 41]
tags: ['fantasy', 'island', 'floating island', 'floating island house', 'unfurnished', 'unfurnished house', 'fantasy house', 'unfurnished fantasy house']
