name: The Puppet (Five Nights at Freddy's)
dims: [15, 16, 3]
tags: ['video game character', 'video game', 'pixel art', 'fnaf', 'the puppet', 'video game character', 'video game', 'pixel art', 'the puppet']
