name: Flash Statue
dims: [16, 31, 8]
tags: ['fictional', 'character', 'superhero', 'comic book character', 'dc comics', 'tv series character', 'comic book character', 'dc comics', 'tv series character']
