name: Modern Beach House
dims: [19, 10, 23]
tags: ['modern house', ' building', ' house', 'modern beach house', 'beach house', 'modern house', ' building', ' house', 'modern beach house', 'beach house']
