name: Korra Statue (The Legend of Korra)
dims: [16, 33, 9]
tags: [' statue', 'cartoon character', 'cartoon', 'korra statue', 'legend of korra', ' statue', 'cartoon character', 'korra statue', 'legend of korra']
