name: Skyrim Nordic Small House 1
dims: [11, 12, 15]
tags: ['skyrim', 'nordic', 'viking', 'small house', ' house', 'nordic house', 'small nordic house', 'medieval nordic house', ' viking house', 'small viking house']
