name: The Simpsons House
dims: [45, 36, 59]
tags: ['building', 'maggie simpson', 'the simpsons', 'lisa simpson', 'bart simpson', 'marge simpson', 'homer simpson', 'house', 'cartoon', 'maggie simpson', 'the simpsons', 'lisa simpson', 'bart simpson', 'marge simpson', 'homer simpson']
