name: Simple Rustic Small Survival House
dims: [15, 17, 18]
tags: ['survival house', ' building', ' house', 'small survival house', 'simple rustic house', 'survival house', ' building', ' house', 'small survival house', 'simple rustic house']
