name: Fantasy Village Pub
dims: [18, 20, 23]
tags: [' tavern', 'pub', 'fantasy', 'fantasy tavern', 'fantasy village', 'fantasy pub', ' tavern', 'fantasy tavern', 'fantasy village', 'fantasy pub', 'unfurnished']
