name: Dry Bones
dims: [16, 27, 1]
tags: ['fictional', 'cartoon character', 'super mario', 'video game character', 'dry bones', 'cartoon character', 'super mario', 'video game character', 'dry bones', 'pixel art']
