name: Medieval Middle Class House 17
dims: [15, 30, 17]
tags: ['medieval', ' building', ' house', 'middle class house', ' medieval house', ' building', ' house', 'middle class house', ' medieval house']
