name: Diamond Shovel
dims: [14, 14, 1]
tags: ['minecraft item', 'minecraft tool', 'item', 'diamond', 'shovel', 'diamond shovel', 'diamond tool', 'minecraft item', 'minecraft tool', 'diamond shovel', 'diamond tool', 'pixel art']
