name: Purple Suburban House
dims: [18, 9, 15]
tags: ['modern house', 'suburb', 'suburban house', ' building', ' house', 'purple suburban house', 'modern house', 'suburban house', ' building', ' house', 'purple suburban house']
