name: Bonnie (Five Nights at Freddy's)
dims: [26, 44, 1]
tags: ['fictional', 'video game character', 'video game', 'pixel art', 'fnaf', 'toy bonnie', 'bonnie', 'video game character', 'video game', 'pixel art', 'toy bonnie']
