name: Diamond Hoe
dims: [12, 14, 1]
tags: ['minecraft item', 'minecraft tool', 'item', 'diamond', 'diamond tool', 'diamond hoe', 'hoe', 'minecraft item', 'minecraft tool', 'diamond tool', 'diamond hoe', 'pixel art']
