name: Freddy Fazbear (Five Nights at Freddy's)
dims: [31, 45, 1]
tags: ['video game character', 'video game', 'pixel art', 'freddy fazbear', 'fnaf', 'video game character', 'video game', 'pixel art', 'freddy fazbear']
