name: Huge Modern Apartment Building
dims: [39, 54, 36]
tags: ['modern', 'apartment', 'downtown', ' building', ' building', 'modern house', 'apartment building', 'skyscraper', 'apartment skyscraper']
