name: Wonder Woman Statue
dims: [16, 32, 8]
tags: [' statue', 'fictional', 'superhero', 'movie character', 'cartoon character', 'comic book character', 'dc comics', 'wonder woman', ' statue', 'movie character', 'cartoon character', 'comic book character', 'dc comics', 'wonder woman']
