name: Small Modern House 1
dims: [23, 8, 30]
tags: ['modern house', 'small house', ' building', 'small modern house', ' house', 'modern house', 'small house', ' building', 'small modern house', ' house']
