name: Maggie Simpson Statue
dims: [14, 24, 14]
tags: ['statue', 'fictional', 'character', 'cartoon character', 'maggie simpson', 'the simpsons', 'cartoon character', 'maggie simpson', 'the simpsons']
