name: Windhelm-inspired House 1
dims: [31, 20, 25]
tags: ['medieval', ' building', ' house', ' medieval house', 'skyrim', 'windhelm-inspired house', ' building', ' house', ' medieval house', 'windhelm-inspired house']
