name: Small &amp; Cosy Medieval House
dims: [10, 11, 10]
tags: ['medieval', ' building', 'small medieval house', ' house', 'cosy medieval house', ' building', 'small medieval house', ' house', 'cosy medieval house']
