name: Small Suburban House
dims: [23, 20, 26]
tags: ['small house', 'suburban house', ' building', ' house', 'small suburban house', 'small house', 'suburban house', ' building', ' house', 'small suburban house']
