name: Luigi
dims: [12, 16, 1]
tags: ['fictional', 'character', 'cartoon character', 'super mario', 'video game character', 'luigi', 'cartoon character', 'super mario', 'video game character', 'pixel art']
