name: Unfurnished Medieval Windmill
dims: [17, 27, 12]
tags: ['medieval', 'medieval windmill', ' medieval house', 'big medieval windmill', 'medieval windmill', ' medieval house', 'big medieval windmill']
