name: Modern Suburban House with Pool
dims: [21, 10, 22]
tags: ['modern house', 'suburb', 'suburban house', ' building', ' house', 'modern suburban house', 'house with pool', 'modern house', 'suburban house', ' building', ' house', 'modern suburban house', 'house with pool']
