name: Agent Coulson Statue (The Avengers)
dims: [16, 32, 9]
tags: [' statue', 'movie character', 'the avengers', 'agent coulson statue', ' statue', 'movie character', 'the avengers', 'agent coulson statue']
