name: Bloody Herobrine Survival House
dims: [16, 17, 25]
tags: ['building', 'house', 'survival', 'survival house', 'bloody herobrine survival house', 'survival house', 'bloody herobrine survival house']
