name: Hulk Statue
dims: [18, 32, 8]
tags: ['statue', 'fictional', 'character', 'superhero', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'hulk', 'movie character', 'cartoon character', 'comic book character']
