name: Waddles the Pig (Gravity Falls)
dims: [127, 109, 1]
tags: ['cartoon character', 'cartoon', 'pixel art', 'gravity falls', 'waddles the pig', 'cartoon character', 'pixel art', 'gravity falls', 'waddles the pig']
