name: Lisa Simpson Statue
dims: [14, 36, 9]
tags: ['statue', 'fictional', 'character', 'cartoon character', 'tv series character', 'the simpsons', 'lisa simpson', 'cartoon character', 'tv series character', 'the simpsons', 'lisa simpson']
