name: Fantasy Steampunk House 2
dims: [19, 16, 14]
tags: ['fantasy', 'fantasy house', 'unfurnished fantasy house', 'small house', 'small steampunk house', 'steampunk house', 'unfurnished', 'unfurnished house']
