name: Mini Castle
dims: [23, 24, 19]
tags: ['medieval', 'small castle', ' castle', ' medieval house', 'medieval castle', 'medieval small castle', 'mini castle', 'small castle', ' castle', ' medieval house', 'medieval castle', 'medieval small castle', 'mini castle']
