name: Jungle House
dims: [12, 42, 13]
tags: ['wooden house', 'jungle house', 'small wooden house', ' building', ' house', 'jungle', 'wooden house', 'jungle house', 'small wooden house', ' building', ' house']
