name: Walter White (Breaking Bad)
dims: [18, 20, 1]
tags: ['fictional', 'video game character', 'breaking bad', 'pixel art', 'walter white', 'video game character', 'breaking bad', 'pixel art', 'walter white']
