name: Jason Voorhees (Friday the 13th)
dims: [43, 40, 1]
tags: ['movie character', 'pixel art', 'friday the 13th', 'jason voorhees', 'movie character', 'pixel art', 'friday the 13th', 'jason voorhees']
