name: Fantasy Steampunk House 7
dims: [13, 30, 21]
tags: ['fantasy', 'fantasy house', 'unfurnished fantasy house', 'steampunk', 'steampunk house', 'unfurnished', 'unfurnished house', 'small steampunk house']
