name: Batman 
dims: [31, 37, 1]
tags: ['superhero', 'movie character', 'cartoon character', 'batman', 'comic book character', 'pixel art', 'movie character', 'cartoon character', 'comic book character', 'pixel art']
