name: Fantasy Steampunk House 4
dims: [21, 29, 21]
tags: ['fantasy', 'fantasy house', 'unfurnished fantasy house', 'steampunk', 'small steampunk house', 'steampunk house', 'unfurnished', 'unfurnished house']
