name: SpongeBob SquarePants Statue
dims: [31, 47, 13]
tags: [' statue', 'fictional', 'character', 'cartoon character', 'tv series character', 'spongebob', 'spongebob squarepants', 'nickelodeon', ' statue', 'cartoon character', 'tv series character', 'spongebob squarepants']
