name: Superman Pixel Art
dims: [21, 23, 1]
tags: ['superhero', 'movie character', 'cartoon character', 'comic book character', 'superman', 'pixel art', 'movie character', 'cartoon character', 'comic book character', 'pixel art']
