name: Two-Storey Medieval Inn
dims: [30, 18, 19]
tags: ['medieval', 'inn', ' building', 'medieval house', 'medieval inn', 'two-storey medieval inn', ' building', 'medieval house', 'medieval inn', 'two-storey medieval inn']
