name: Medieval Island Village Inn
dims: [28, 23, 31]
tags: ['medieval', 'inn', 'medieval inn', ' medieval house', 'island', 'big village house', 'village', 'medieval inn', ' medieval house', 'big village house']
