name: Freddy Statue
dims: [16, 36, 8]
tags: ['statue', 'fictional', 'character', 'video game character', 'freddy', "five nights at freddy's", 'video game character', "five nights at freddy's", 'horror']
