name: Daredevil Statue
dims: [16, 33, 8]
tags: [' statue', 'fictional', 'character', 'superhero', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'tv series character', 'daredevil', ' statue', 'movie character', 'cartoon character', 'comic book character', 'tv series character']
