name: Katniss Everdeen Statue (Hunger Games)
dims: [16, 32, 16]
tags: [' statue', 'movie character', 'katniss everdeen statue', 'hunger games', ' statue', 'movie character', 'katniss everdeen statue', 'hunger games']
