name: Medieval Rural Stable
dims: [14, 6, 8]
tags: ['horse stable', 'medieval stable', 'medieval barn/stables', 'medieval horse stable', 'horse stable', 'medieval stable', 'medieval barn/stables', 'medieval horse stable']
