name: Cookie Monster Statue
dims: [29, 31, 1]
tags: ['fictional', 'tv series character', 'pixel art', 'cookie monster', 'sesame street', 'muppet', 'tv series character', 'pixel art', 'cookie monster', 'sesame street']
