name: Small Medieval Rustic Village House
dims: [9, 8, 7]
tags: ['medieval', ' building', 'small medieval house', ' house', 'rustic village house', ' building', 'small medieval house', ' house', 'rustic village house']
