name: Gothic Tavern
dims: [17, 18, 18]
tags: ['medieval', ' tavern', ' building', ' house', ' medieval house', 'gothic bridge', 'gothic tavern', ' tavern', ' building', ' house', ' medieval house', 'gothic bridge', 'gothic tavern']
