name: Survival Offshore Ocean Fishing House 
dims: [21, 26, 22]
tags: ['house', 'survival house', ' building', 'ocean fishing house', 'survival offshore house', 'survival house', ' building', 'ocean fishing house', 'survival offshore house']
