name: Emirates Crown, Dubai
dims: [47, 127, 47]
tags: ['modern', ' building', 'high rise building', 'modern luxury building', 'skyscraper', ' building', 'high rise building', 'modern luxury building']
