name: Diamond Pickaxe
dims: [13, 13, 1]
tags: ['diamond tools', 'minecraft item', 'minecraft tool', 'item', 'diamond', 'diamond pickaxe', 'diamond tools', 'minecraft item', 'minecraft tool', 'diamond pickaxe', 'pixel art']
