name: King Statue
dims: [16, 32, 10]
tags: [' statue', 'movie character', 'cartoon character', 'comic book character', 'tv series character', 'video game character', 'king', 'people', ' statue', 'movie character', 'cartoon character', 'comic book character', 'tv series character', 'video game character']
