name: Diamond Leggings
dims: [10, 13, 1]
tags: ['diamond armor', 'minecraft item', 'item', 'diamond', 'leggings', 'diamond leggings', 'diamond armor', 'minecraft item', 'diamond leggings', 'pixel art']
