name: Bergfried Defensive Keep
dims: [26, 25, 26]
tags: ['bergfried', ' keep', 'medieval keep', 'medieval keep/castle', 'stone keep', 'defensive structure', 'medieval', 'unfurnished', 'exterior only']
