name: Small Survival Victorian House
dims: [13, 15, 14]
tags: [' building', ' house', 'small survival house', 'survival victorian house', 'small victorian house', ' building', ' house', 'small survival house', 'survival victorian house', 'small victorian house']
