name: Fantasy Village Small House 3
dims: [18, 10, 11]
tags: ['small house', ' house', 'fantasy house', 'fantasy', 'fantasy village house', 'small house', ' house', 'fantasy house', 'fantasy village house']
