name: Spider-Man Statue
dims: [16, 32, 8]
tags: ['statue', 'fictional', 'character', 'spiderman', 'superhero', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'movie character', 'cartoon character', 'comic book character']
