name: Small Modern Stone House
dims: [17, 6, 26]
tags: ['modern house', ' stone house', ' building', ' house', 'small stone house', 'modern stone house', 'modern house', ' stone house', ' building', ' house', 'small stone house', 'modern stone house']
