name: Diamond Axe
dims: [12, 14, 1]
tags: ['minecraft item', 'minecraft tool', 'item', 'diamond', 'diamond tool', 'diamond axe', ' axe', 'minecraft item', 'minecraft tool', 'diamond tool', 'diamond axe', ' axe', 'pixel art']
