name: Fully Automatic Melon Farm
dims: [7, 5, 6]
tags: ['redstone', 'working mechanism', 'machine', 'fully automatic melon farm', 'melon farm', 'working mechanism', 'fully automatic melon farm', 'melon farm']
