name: Small Medieval House 2
dims: [15, 14, 21]
tags: ['medieval', 'small house', ' building', 'small medievil house', 'medieval house', 'small house', ' building', 'small medievil house', 'medieval house']
