name: Fishing Village House 1
dims: [25, 13, 16]
tags: ['fishing', 'wooden house', ' house', 'rustic village house', 'fishing house', 'wooden house', ' house', 'rustic village house', 'fishing house']
