name: Captain America Statue
dims: [16, 32, 8]
tags: [' statue', 'fictional', 'superhero', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'captain america', ' statue', 'movie character', 'cartoon character', 'comic book character', 'captain america']
