name: Simple Medieval Castle Wall Gate
dims: [23, 15, 26]
tags: ['medieval', ' building', ' house', 'simple medieval gate', 'castle wall gate', ' building', ' house', 'simple medieval gate', 'castle wall gate']
