name: Gunter the Penguin
dims: [28, 29, 1]
tags: ['fictional', 'cartoon character', 'tv series character', 'pixel art', 'gunter', 'adventure time', 'cartoon character', 'tv series character', 'pixel art', 'adventure time']
