name: Super Mario Mushroom Statue
dims: [16, 17, 15]
tags: [' statue', 'fictional', 'cartoon character', 'super mario', 'video game character', 'mushroom', ' statue', 'cartoon character', 'super mario', 'video game character']
