name: Bart Simpson Statue
dims: [14, 35, 9]
tags: [' statue', 'fictional', 'character', 'cartoon character', 'tv series character', 'the simpsons', 'bart simpson', ' statue', 'cartoon character', 'tv series character', 'the simpsons', 'bart simpson']
