name: Suburban Quartz House
dims: [19, 15, 26]
tags: ['house', 'quartz house', 'quartz', 'modern house', 'suburban house', ' building', 'suburban quartz house', 'quartz house', 'modern house', 'suburban house', ' building', 'suburban quartz house']
