name: Thor Statue
dims: [16, 35, 8]
tags: [' statue', 'fictional', 'character', 'superhero', 'movie character', 'marvel', 'cartoon character', 'comic book character', 'thor', ' statue', 'movie character', 'cartoon character', 'comic book character']
