name: Bat-Man Statue
dims: [16, 31, 8]
tags: ['statue', 'fictional', 'character', 'superhero', 'movie character', 'cartoon character', 'batman', 'comic book character', 'movie character', 'cartoon character', 'comic book character']
