name: Modern Quartz House
dims: [23, 13, 21]
tags: ['quartz house', 'modern house', ' building', ' house', 'modern quartz house', 'quartz house', 'modern house', ' building', ' house', 'modern quartz house']
