name: Medieval Wooden Shack
dims: [9, 10, 16]
tags: ['wooden', 'wooden house', 'medieval', 'small wooden house', ' medieval house', 'unfurnished', 'wooden house', 'small wooden house', ' medieval house']
