name: Medieval Low Class Stone House
dims: [9, 7, 12]
tags: ['medieval', ' stone house', ' building', ' house', 'low class house', ' medieval house', ' stone house', ' building', ' house', 'low class house', ' medieval house']
