name: Small Medieval Town House 1
dims: [17, 14, 25]
tags: ['small house', ' building', ' house', 'medieval town house', ' medieval house', 'small house', ' building', ' house', 'medieval town house', ' medieval house']
