name: Small Enchanting Hut
dims: [9, 6, 9]
tags: ['wooden cabin', 'hut', 'small wooden house', ' building', ' house', 'small enchanting hut', 'wooden cabin', 'small wooden house', ' building', ' house', 'small enchanting hut']
