name: Medieval City Tower and Keep
dims: [75, 76, 37]
tags: ['medieval', 'keep', 'medieval house', 'medieval tower', 'medieval city tower', 'city tower', 'medieval keep', 'medieval house', 'medieval tower', 'medieval city tower', 'city tower', 'medieval keep']
