name: Sanic Statue
dims: [9, 10, 6]
tags: [' statue', 'video game character', 'video game', 'sonic', 'outdoor decoration', 'decoration', 'sanic', ' statue', 'video game character', 'video game', 'outdoor decoration']
