name: Diamond Chestplate
dims: [14, 13, 1]
tags: ['diamond armor', 'minecraft item', 'item', 'diamond', 'diamond chestplate', 'chestplate', 'pixel art', 'diamond armor', 'minecraft item', 'diamond chestplate', 'pixel art']
