name: Superman Statue
dims: [16, 32, 8]
tags: [' statue', 'fictional', 'character', 'movie character', 'cartoon character', 'comic book character', 'dc comics', 'superman', ' statue', 'movie character', 'cartoon character', 'comic book character', 'dc comics']
