name: Medieval City Tower 2
dims: [43, 44, 48]
tags: ['medieval', 'city', 'medieval house', 'medieval tower', 'medieval city tower', 'city tower', 'medieval house', 'medieval tower', 'medieval city tower', 'city tower']
