name: Marge Simpson Statue
dims: [16, 45, 9]
tags: [' statue', 'fictional', 'character', 'cartoon character', 'tv series character', 'the simpsons', 'marge simpson', ' statue', 'cartoon character', 'tv series character', 'the simpsons', 'marge simpson']
