name: Toy Bonnie (Five Nights at Freddy's)
dims: [114, 127, 1]
tags: ['video game character', 'video game', 'pixel art', 'fnaf', 'toy bonnie', 'video game character', 'video game', 'pixel art', 'toy bonnie']
