name: Big Victorian House
dims: [63, 28, 76]
tags: [' building', ' house', 'victorian house', 'big victorian house', 'big house', ' building', ' house', 'victorian house', 'big victorian house', 'big house']
