name: Simple Survival Modern House
dims: [18, 5, 13]
tags: ['survival', ' building', 'simple house', ' house', 'survival modern house', ' building', 'simple house', ' house', 'survival modern house']
