name: Medieval Fantasy Mage Tower
dims: [15, 41, 13]
tags: ['medieval', 'tower', ' building', 'medieval fantasy tower', 'medieval mage tower', ' building', 'medieval fantasy tower', 'medieval mage tower']
