name: Medieval Tudor Storage
dims: [10, 12, 18]
tags: ['medieval', 'item storage', 'medieval storage warehouse', 'storage building', 'tudor', 'item storage', 'medieval storage warehouse', 'storage building']
