name: Small Medieval House 7
dims: [13, 16, 15]
tags: ['medieval', 'small house', ' building', 'small medieval house', 'medieval house', 'small house', ' building', 'small medieval house', 'medieval house']
