name: Small Modern House 4
dims: [18, 7, 24]
tags: ['modern house', 'small house', ' building', 'small modern house', ' house', 'modern house', 'small house', ' building', 'small modern house', ' house']
