name: Medieval Nordic House 1
dims: [31, 14, 27]
tags: ['medieval', ' building', ' house', ' medieval house', 'medieval nordic house', ' building', ' house', ' medieval house', 'medieval nordic house']
