name: Secret Staircase Room
dims: [6, 5, 5]
tags: ['redstone', 'working mechanism', 'machine', ' mechanisms', 'secret staircase room', 'secret passageways', 'working mechanism', ' mechanisms', 'secret staircase room', 'secret passageways']
