name: Medieval Middle Class House 20
dims: [22, 13, 15]
tags: ['medieval', ' building', ' house', 'middle class house', ' medieval house', ' building', ' house', 'middle class house', ' medieval house']
