name: Hulk Pixel Art
dims: [21, 23, 1]
tags: ['fictional', 'superhero', 'cartoon character', 'comic book character', 'hulk', '8bit', 'pixel art', 'cartoon character', 'comic book character', 'pixel art']
